# Generated by Django 3.0.5 on 2020-05-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheInimicalWood', '0023_auto_20200518_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='belongs_to_hero',
        ),
    ]
